---
---

display_url: https://dtc-innovation.org
backend:
  name: github
  repo: dtc-innovation/dtc-innovation.org
slug:
  encoding: ascii
  clean_accents: true
editor:
  preview: true

media_folder: "images/uploads"
# publish_mode: editorial_workflow

collections:
  - name: "writing"
    label: "Journal"
    label_singular: "entry"
    folder: "collections/_posts"
    sort: "date:desc"
    create: true
    slug: "{% raw %}{{year}}-{{month}}-{{day}}-{{slug}}{% endraw %}"
    fields:
      - label: "Title"
        name: "title"
        tagname: "h1"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        tagname: "h2"
        widget: "string"
        required: false
      - label: "Writing Body"
        name: "body"
        widget: "markdown"
      - label: "Cover image"
        name: image
        widget: "image"
        required: false
      - label: "Language"
        name: "lang"
        widget: "select"
        options: ["", "fr", "en"]
        required: false
      - label: "Categories"
        name: "category"
        widget: "string"
        required: false
      - label: "Linked Project"
        name: "projects"
        widget: "relation"
        collection: "project_fr"
        valueField: "name"
        displayFields: ["name", "customer"]
        searchFields: ["name", "short_description"]
        required: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD hh:mm:ss"
  - name: "decision"
    label: "Décisions"
    label_singular: "decision"
    folder: "collections/_decisions"
    sort: "date:desc"
    create: true
    slug: "{% raw %}{{year}}-{{month}}-{{day}}{% endraw %}"
    fields:
      - label: "Titre"
        name: "title"
        tagname: "h1"
        widget: "string"
      - label: "Décision(s)"
        name: "body"
        widget: "markdown"
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD hh:mm:ss"
  - name: "customer"
    label: "Clients"
    label_singular: "customer"
    folder: "collections/_customers"
    sort: "name:asc"
    create: true
    fields:
      - label: "Nom"
        name: "title"
        tagname: "h1"
        widget: "string"
      - label: "Identifiant"
        name: "uid"
        widget: "string"
        pattern: ["[a-zA-Z0-9-]+", "Uniquement des lettres, chiffres et trait d'union."]
      - label: "Site web"
        name: "website"
        widget: "string"
      - label: "Pays"
        name: "location"
        widget: "select"
        options: ["France", "Canada", "Royaume-Uni"]
  - name: "project_fr"
    label: "Projets (Français)"
    label_singular: "project"
    folder: "collections/_projects_fr"
    create: true
    fields:
      - label: "Nom du projet"
        name: "name"
        widget: "string"
        tagname: "h1"
      - label: "Proposition de valeur"
        name: "short_description"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image de couverture"
        name: image
        widget: "image"
        required: false
      - label: "Client"
        name: "customer"
        widget: "relation"
        collection: "customer"
        displayFields: ["name"]
        searchFields: ["name", "url"]
        valueField: "uid"
        required: false
      - label: "Mots-clés"
        name: "labels"
        widget: "list"
        required: false
      - label: "Ordre d'affichage"
        name: "highlights_order"
        widget: "number"
        required: false
      - label: "Étape d'avancement"
        name: "current_stage"
        widget: "string"
        required: false
      - label: "Prochaine étape"
        name: "next_stage"
        widget: "string"
        required: false
      - label: "Ressources"
        name: "resources"
        widget: "list"
        required: false
        allow_add: true
        fields:
          - label: "Nom"
            name: "name"
            widget: "string"
            required: true
          - label: "URL"
            name: "url"
            widget: "string"
            required: true
  - name: "project_en"
    label: "Projets (Anglais)"
    label_singular: "project"
    folder: "collections/_projects_en"
    create: true
    fields:
      - label: "Nom du projet"
        name: "name"
        widget: "string"
        tagname: "h1"
      - label: "Proposition de valeur"
        name: "short_description"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Image de couverture"
        name: image
        widget: "image"
        required: false
      - label: "Client"
        name: "customer"
        widget: "relation"
        collection: "customer"
        displayFields: ["name"]
        searchFields: ["name", "url"]
        valueField: "uid"
        required: false
      - label: "Mots-clés"
        name: "labels"
        widget: "list"
        required: false
      - label: "Ordre d'affichage"
        name: "highlights_order"
        widget: "number"
        required: false
      - label: "Étape d'avancement"
        name: "current_stage"
        widget: "string"
        required: false
      - label: "Prochaine étape"
        name: "next_stage"
        widget: "string"
        required: false
      - label: "Ressources"
        name: "resources"
        widget: "list"
        required: false
        allow_add: true
        fields:
          - label: "Nom"
            name: "name"
            widget: "string"
            required: true
          - label: "URL"
            name: "url"
            widget: "string"
            required: true
